name: Pipeline

on: [push]

env:
    ARTIFACT_NAME: my_artifact

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: run program
              run: python main.py

    build:
        name: Build
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: upload artifact
              uses: actions/upload-artifact@v2
              with:
                name: ${{ env.ARTIFACT_NAME }}
                path: .